### ISSUE TITLE
test: case file format

### ISSUE THREAD

**Issue by kindy** [kindy/babel-plugin-transform-v-jsx#1]
reuse IDE's js syntax support, js code in yml can not be highlighted.

```js
// test/005-model.js.t

module.exports = {
  skip: true,
  cases: [{
    in:
      <input v:model={this.a} />,
    out:
      <input value={this.a} onChange={val => this.a = val} />,
  }, {
    in:
      <A v:model={{val: this.a.b}} />,
    out:
      <A val={this.a.b} onChange={val => this.a.b = val} />,
  }],
}
```

compare with yml:

```yml
# test/005-model.yml

skip: true
cases:
  - i: |
      <input v:model={this.a} />
    o: |
      <input value={this.a} onChange={val => this.a = val} />

  - i: |
      <A v:model={{val: this.a.b}} />
    o: |
      <A val={this.a.b} onChange={val => this.a.b = val} />
```
